default:
  customer:
    value:
      - prod1
      - prod2
      - prod3

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

logging:
  level:
    org.springframework.cloud.config: INFO