server:
  port:8081

default:
  customer:
    value:
      - customer1
      - customer2
      - customer3
      - customer4


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - refresh
logging:
  level:
    org.springframework.cloud.config: DEBUG
